apiVersion: v1
kind: ReplicationController
metadata:
  name: ruby-jenkernetes-slave
spec:
  template:
    metadata:
      name: jenkins-ruby-slave
      labels:
        role: slave
        language: ruby
    spec:
        containers:
          -
            name: jenkins-ruby-slave
            image: bshaffer/ruby-jenkernetes-slave
            imagePullPolicy: Always
            volumeMounts:
              - mountPath: /var/run/docker.sock
                name: docker-sock
              - mountPath: /usr/bin/docker
                name: docker-bin
              - mountPath: /tmp
                name: docker-tmp
        volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock
          - name: docker-bin
            hostPath:
              path: /usr/bin/docker
          - name: docker-tmp
            hostPath:
              path: /tmp
