package org.jenkinsci.plugins.kubernetesworkflowsteps;

import com.github.kubernetes.java.client.model.Service;

import org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl;
import org.kohsuke.stapler.DataBoundConstructor;

import hudson.Extension;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class CreateServiceStep extends KubeStep<Service, Service> {

  /**
   * @param obj
   */
  @DataBoundConstructor
  public CreateServiceStep(Service obj) {
    super(obj);
    // TODO(elibixby): Auto-generated constructor stub
  }
  
  public static class Execution extends KubeStepExecution<Service, Service, CreateServiceStep>{

    /* (non-Javadoc)
     * @see org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution#run()
     */
    @Override
    protected Service run() throws Exception {
      return this.getKubeClient().createService(step.arg);
      
    }
    
  }
  
  @Extension
  public static class DescriptorImpl extends AbstractStepDescriptorImpl{
    public DescriptorImpl() {
      super(Execution.class);
    }

    @Override public String getFunctionName() {
      return "kube_create_service";
    }

    @Override public String getDisplayName() {
      return "Create a Kubernetes Service by Id";
    }
  }

}
