package org.jenkinsci.plugins.kubernetesworkflowsteps;

import com.github.kubernetes.java.client.model.ReplicationController;

import org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl;
import org.kohsuke.stapler.DataBoundConstructor;

import hudson.Extension;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class CreateReplicationControllerStep extends
    KubeStep<ReplicationController, ReplicationController> {

  /**
   * @param obj
   */
  @DataBoundConstructor
  public CreateReplicationControllerStep(ReplicationController obj) {
    super(obj);
    // TODO(elibixby): Auto-generated constructor stub
  }

  public static class Execution extends KubeStepExecution<ReplicationController, ReplicationController, CreateReplicationControllerStep>{

    /* (non-Javadoc)
     * @see org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution#run()
     */
    @Override
    protected ReplicationController run() throws Exception {
      return this.getKubeClient().createReplicationController(step.arg);
      
    }
    
  }
  
  @Extension
  public static class DescriptorImpl extends AbstractStepDescriptorImpl{
    public DescriptorImpl() {
      super(Execution.class);
    }

    @Override public String getFunctionName() {
      return "kube_create_pod";
    }

    @Override public String getDisplayName() {
      return "Create a Kubernetes ReplicationController";
    }
  }
  
}
