package org.jenkinsci.plugins.kubernetesworkflowsteps;

import com.github.kubernetes.java.client.exceptions.Status;

import org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl;
import org.kohsuke.stapler.DataBoundConstructor;

import hudson.Extension;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class DeleteReplicationControllerStep extends KubeStep<String, Status> {

  /**
   * @param obj
   */
  @DataBoundConstructor
  public DeleteReplicationControllerStep(String obj) {
    super(obj);
    // TODO(elibixby): Auto-generated constructor stub
  }

  public static class Execution extends KubeStepExecution<String, Status, DeleteReplicationControllerStep>{

    /* (non-Javadoc)
     * @see org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution#run()
     */
    @Override
    protected Status run() throws Exception {
      return this.getKubeClient().deleteReplicationController(step.arg);
      
    }
    
  }
  
  @Extension
  public static class DescriptorImpl extends AbstractStepDescriptorImpl{
    public DescriptorImpl() {
      super(Execution.class);
    }

    @Override public String getFunctionName() {
      return "kube_delete_replication_controller";
    }

    @Override public String getDisplayName() {
      return "Delete a Kubernetes ReplicationController by Id";
    }
  }
  
}
