package org.jenkinsci.plugins.kubernetesworkflowsteps;

import com.github.kubernetes.java.client.exceptions.Status;

import org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl;
import org.kohsuke.stapler.DataBoundConstructor;

import hudson.Extension;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class DeleteServiceStep extends KubeStep<String, Status> {

  @DataBoundConstructor
  public DeleteServiceStep(String obj) {
    super(obj);
    // TODO(elibixby): Auto-generated constructor stub
  }
  
  public static class Execution extends KubeStepExecution<String, Status, DeleteServiceStep>{

    /* (non-Javadoc)
     * @see org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution#run()
     */
    @Override
    protected Status run() throws Exception {
      return this.getKubeClient().deleteService(step.arg);
      
    }
    
  }
  
  @Extension
  public static class DescriptorImpl extends AbstractStepDescriptorImpl{
    public DescriptorImpl() {
      super(Execution.class);
    }

    @Override public String getFunctionName() {
      return "kube_delete_service";
    }

    @Override public String getDisplayName() {
      return "Delete a Kubernetes Service by Id";
    }
  }

}
