package org.jenkinsci.plugins.kubernetesworkflowsteps;

import com.github.kubernetes.java.client.model.PodList;

import org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl;
import org.kohsuke.stapler.DataBoundConstructor;

import hudson.Extension;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class GetAllPodsStep extends KubeStep<Void, PodList> {

  @DataBoundConstructor
  public GetAllPodsStep() {
    super(null);
  }

  
  public static class Execution extends KubeStepExecution<Void, PodList, GetAllPodsStep>{

    /* (non-Javadoc)
     * @see org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution#run()
     */
    @Override
    protected PodList run() throws Exception {
      return this.getKubeClient().getAllPods();
      
    }
    
  }
  
  @Extension
  public static class DescriptorImpl extends AbstractStepDescriptorImpl{
    public DescriptorImpl() {
      super(Execution.class);
    }

    @Override public String getFunctionName() {
      return "kube_get_all_pods";
    }

    @Override public String getDisplayName() {
      return "Get A PodList containing all Kubernetes Pods";
    }
  }
}
