package org.jenkinsci.plugins.kubernetesworkflowsteps;

import com.github.kubernetes.java.client.model.Pod;

import org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl;
import org.kohsuke.stapler.DataBoundConstructor;

import hudson.Extension;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class GetPodStep extends KubeStep<String, Pod>{

  /**
   * @param obj
   */
  @DataBoundConstructor
  public GetPodStep(String obj) {
    super(obj);
  }
  
  public static class Execution extends KubeStepExecution<String, Pod, GetPodStep>{

    /* (non-Javadoc)
     * @see org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution#run()
     */
    @Override
    protected Pod run() throws Exception {
      return this.getKubeClient().getPod(step.arg);
      
    }
    
  }
  
  @Extension
  public static class DescriptorImpl extends AbstractStepDescriptorImpl{
    public DescriptorImpl() {
      super(Execution.class);
    }

    @Override public String getFunctionName() {
      return "kube_get_pod";
    }

    @Override public String getDisplayName() {
      return "Get a Kubernetes Pod by Id";
    }
  }
}
