package org.jenkinsci.plugins.kubernetesworkflowsteps;

import com.github.kubernetes.java.client.model.ReplicationController;

import org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl;
import org.kohsuke.stapler.DataBoundConstructor;

import hudson.Extension;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class GetReplicationControllerStep extends KubeStep<String, ReplicationController> {

  /**
   * @param obj
   */
  @DataBoundConstructor
  public GetReplicationControllerStep(String obj) {
    super(obj);
    // TODO(elibixby): Auto-generated constructor stub
  }

  public static class Execution extends KubeStepExecution<String, ReplicationController, GetReplicationControllerStep>{

    /* (non-Javadoc)
     * @see org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution#run()
     */
    @Override
    protected ReplicationController run() throws Exception {
      return this.getKubeClient().getReplicationController(step.arg);
      
    }
    
  }
  
  @Extension
  public static class DescriptorImpl extends AbstractStepDescriptorImpl{
    public DescriptorImpl() {
      super(Execution.class);
    }

    @Override public String getFunctionName() {
      return "kube_get_replication_controller";
    }

    @Override public String getDisplayName() {
      return "Get a Kubernetes ReplicationController by Id";
    }
  }
}
