package org.jenkinsci.plugins.kubernetesworkflowsteps;

import com.github.kubernetes.java.client.model.PodList;

import org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl;
import org.kohsuke.stapler.DataBoundConstructor;

import hudson.Extension;

import java.util.Map;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class GetSelectedPodsStep extends KubeStep<Map<String, String>, PodList> {

  /**
   * @param obj
   */
  @DataBoundConstructor
  public GetSelectedPodsStep(Map<String, String> obj) {
    super(obj);
    // TODO(elibixby): Auto-generated constructor stub
  }

  
  public static class Execution extends KubeStepExecution<Map<String,String>, PodList, GetSelectedPodsStep>{

    /* (non-Javadoc)
     * @see org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution#run()
     */
    @Override
    protected PodList run() throws Exception {
      return this.getKubeClient().getSelectedPods(step.arg);
      
    }
    
  }
  
  @Extension
  public static class DescriptorImpl extends AbstractStepDescriptorImpl{
    public DescriptorImpl() {
      super(Execution.class);
    }

    @Override public String getFunctionName() {
      return "kube_get_selected_pods";
    }

    @Override public String getDisplayName() {
      return "Get a PodList of Kubernetes Pods by <String,String> label";
    }
  }
}
