package org.jenkinsci.plugins.kubernetesworkflowsteps;

import org.jenkinsci.plugins.workflow.steps.AbstractStepImpl;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public abstract class KubeStep<T,O> extends AbstractStepImpl {

  
  public transient T arg;
  
  public KubeStep(T obj){   
    arg=obj;
  }

  

}
