package org.jenkinsci.plugins.kubernetesworkflowsteps;

import com.google.gson.Gson;

import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl;
import org.kohsuke.stapler.DataBoundConstructor;

import hudson.Extension;

import java.util.Map;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class KubeCreateStep extends KubeStep {

  public final transient Map<?,?> data;
  
  /**
   * @param resource
   */
  @DataBoundConstructor
  public KubeCreateStep(String resource, Map<?,?> data) {
    super(resource);
    this.data = data;
  }
  
  @Extension public static final class DescriptorImpl extends AbstractStepDescriptorImpl{
    
    public DescriptorImpl() {
      super(Execution.class);
    }
    
    @Override
    public String getFunctionName(){
      return "kube_create";
    }
    
    @Override
    public String getDisplayName(){
      return "Create a resource using the Kubernetes API";
    }
    
  }
  
  public static class Execution extends KubeStepExecution<KubeCreateStep>{

    /* (non-Javadoc)
     * @see org.jenkinsci.plugins.kubernetesworkflowsteps.KubeStepExecution#request()
     */
    @Override
    protected String run() throws Exception {
      StringEntity entity = new StringEntity((new Gson()).toJson(step.data));
      entity.setContentType("application/json");
      HttpPost post = new HttpPost(this.prefix+step.resource);
      post.setEntity(entity);
      return parse(makeCall(post, this.readWriteHost, this.readWritePort));
    }
    
  }

}
