package org.jenkinsci.plugins.kubernetesworkflowsteps;

import org.apache.http.client.methods.HttpGet;
import org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl;
import org.kohsuke.stapler.DataBoundConstructor;

import hudson.Extension;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class KubeGetStep extends KubeStep {


  public transient String id;
  
  /**
   * @param resource
   */
  @DataBoundConstructor
  public KubeGetStep(String resource, String id) {
    super(resource);
    this.id = id;
  }

  @Extension
  public static class DescriptorImpl extends AbstractStepDescriptorImpl{

    public DescriptorImpl() {
      super(Execution.class);
    }
    
    @Override
    public String getFunctionName(){
      return "kube_get";
    }
    
    @Override
    public String getDisplayName(){
      return "Get a resource using the Kubernetes API";
    }
    
  }
  
  
  public static class Execution extends KubeStepExecution<HttpGet, KubeGetStep>{
    
    /* (non-Javadoc)
     * @see org.jenkinsci.plugins.kubernetesworkflowsteps.KubeStepExecution#request()
     */
    @Override
    protected HttpGet request() {
      return new HttpGet("/"+step.resource+"/"+step.id);
    }
  }
}
