package org.jenkinsci.plugins.kubernetesworkflowsteps;

import org.apache.http.client.methods.HttpDelete;
import org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl;
import org.kohsuke.stapler.DataBoundConstructor;

import hudson.Extension;

import java.io.UnsupportedEncodingException;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class KubeDeleteStep extends KubeStep {

  public final transient String id;
  
  /**
   * @param resource
   * @param id
   */
  @DataBoundConstructor
  public KubeDeleteStep(String resource, String id) {
    super(resource);
    this.id = id;
  }
  
  @Extension public static final class DescriptorImpl extends AbstractStepDescriptorImpl{


    public DescriptorImpl() {
      super(Execution.class);
    }
    
    @Override
    public String getFunctionName(){
      return "kube_delete";
    }
    
    @Override
    public String getDisplayName(){
      return "Delete a resource using the Kubernetes API";
    }
    
  }
  
  
  public static final class Execution extends KubeStepExecution<HttpDelete, KubeDeleteStep>{
    
    /* (non-Javadoc)
     * @see org.jenkinsci.plugins.kubernetesworkflowsteps.KubeStepExecution#request()
     */
    @Override
    protected HttpDelete request() throws UnsupportedEncodingException {
      return new HttpDelete("/"+step.resource+"/"+step.id);
    }
    
  }
  

}
