package org.jenkinsci.plugins.kubernetesworkflowsteps;

import org.jenkinsci.plugins.workflow.steps.AbstractStepImpl;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public abstract class KubeStep extends AbstractStepImpl{

  public final transient String resource;
  
  public KubeStep(String resource){
    this.resource = resource;
  }
  
}
