package org.jenkinsci.plugins.kubernetesworkflowsteps;

import org.apache.http.client.methods.HttpPost;
import org.jenkinsci.plugins.workflow.steps.AbstractStepDescriptorImpl;
import org.kohsuke.stapler.DataBoundConstructor;

import hudson.Extension;

import java.io.UnsupportedEncodingException;

/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class KubeCreateStep extends KubeStep {

  public final transient Object payload;
  
  /**
   * @param resource
   * @throws UnsupportedEncodingException 
   */
  @DataBoundConstructor
  public KubeCreateStep(String resource, Object payload) throws UnsupportedEncodingException {
    super(resource);
    this.payload = payload;
  }
  
  @Extension public static final class DescriptorImpl extends AbstractStepDescriptorImpl{
    
    public DescriptorImpl() {
      super(Execution.class);
    }
    
    @Override
    public String getFunctionName(){
      return "kube_create";
    }
    
    @Override
    public String getDisplayName(){
      return "Create a resource using the Kubernetes API";
    }
    
  }
  
  public static class Execution extends KubeStepExecution<KubeCreateStep>{

    /* (non-Javadoc)
     * @see org.jenkinsci.plugins.kubernetesworkflowsteps.KubeStepExecution#request()
     */
    @Override
    protected Object run() throws Exception {
      HttpPost post = new HttpPost(this.prefix+step.resource);
      post.setEntity(toEntity(step.payload));
      return parse(makeCall(post, this.readWriteHost, this.readWritePort));
    }
    
  }

}
